### PR TITLE
Converted useDataPkgs.Rnw to Rmd (updated)

### PR DESCRIPTION
**Pull request by manviyadu1shi**

### CODE REVIEW

**Comment by jwokaty** [comment]
@manviyadu1shi Thanks for your PR! It's looks good. I made some small changes you can see at https://github.com/Bioconductor/annotate/pull/10/commits/f1d810aa77e7e689aee62319efbc6837956d2730 since I noticed `KEGG.db` was removed from Bioconductor, the GO terms needed to have the `:` escaped, and the authors should be split. I'm just going to ask a teammate about `KEGG.db` then I will merge your PR. :)

**Comment by manviyadu1shi** [comment]
@jwokaty Thanks a lot! Learnt a lot through my first PR and always up for any help or additions. Waiting for my first ever PR merged at Bioc :) Do let me know if it still needs any edits!

**Comment by jwokaty** [comment]
@manviyadu1shi I've merged your PR. We'll see your version of the vignette on https://bioconductor.org/packages/3.19/bioc/html/annotate.html in the next few days. Thanks for your contribution to Bioconductor!

**Comment by manviyadu1shi** [comment]
> @manviyadu1shi I've merged your PR. We'll see your version of the vignette on https://bioconductor.org/packages/3.19/bioc/html/annotate.html in the next few days. Thanks for your contribution to Bioconductor!

Thankyou so much! Looking forward to more contributions.

**Pull request merged**
